def analizartexto():
    print("Analizador de textos")
    frase = input("Pon un texto o frase ")
    numcaracteres = len(frase)
    palabras = frase.split()
    numpalabras = len(palabras)
    mayusculas = frase.upper()
    minusculas = frase.lower()
    invertida = frase[::-1]
    buscar = input("¿Qué palabra desea buscar? ")
    ocurrencias = frase.count(buscar)
    reemplazar = input(f"¿Con qué palabra desea reemplazar '{buscar}'?: ")
    nueva_frase = frase.replace(buscar, reemplazar)
    print("Resultado:")
    print(f"Cantidad: {numcaracteres}")
    print(f"Palabras: {numpalabras}")
    print(f"En mayúsculas: {mayusculas}")
    print(f"En minúsculas: {minusculas}")
    print(f"Invertida: {invertida}")
    print(f"Ocurrencias de '{buscar}': {ocurrencias}")
    print(f"Frase con reemplazo: {nueva_frase}")
analizartexto()
